### ISSUE TITLE
Transfer to Fortran-lang organization?

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/test-drive#2]
This project was originally developed as light-weight testing framework for TOML Fortran and the Fortran package manager, where it has been redistributed within the testsuite. There are now a couple of redistributed variants around, mostly MIT or Apache-2.0 licensed:

- https://github.com/fortran-lang/fpm/blob/master/test/fpm_test/testsuite.f90
- https://github.com/toml-f/toml-f/blob/main/test/tftest/testsuite.f90
- https://github.com/LKedward/fhash/blob/master/test/TestLite.f90
- https://github.com/grimme-lab/mctc-lib/blob/main/src/mctc/env/testing.f90

We discussed about this and other testing frameworks at @fortran-lang in several issues and I offered to transfer it to @fortran-lang:

- https://github.com/fortran-lang/fpm/issues/176
- https://github.com/fortran-lang/stdlib/issues/162
- https://github.com/fortran-lang/fftpack/issues/12
- https://github.com/fortran-lang/stdlib/pull/494

cc @certik @zoziha @everythingfunctional @milancurcic @lkedward @hsnyder @jvdp1

**Comment by zoziha** [comment]
I hope that `fortran-lang` can maintain a testing-framework, and it will go further with the help of `fortran-lang` organization. It will be standardized, accepted and improved by the community, which is a very far-reaching good thing!
Thank you for your generous donation (`test-drive`) to fortran-lang!🎉

**Comment by jvdp1** [comment]
That sounds like a great idea to me, especially if it is used by fpm and stdlib. Thank you @awvwgk

**Comment by certik** [comment]
I think this looks good as a testing framework. Why not simplify:
```
            call check(error, all(input == expected))
            if (allocated(error)) return
```
to:
```
            if (check(error, all(input == expected))) return
```
Beyond that, the only other way to simplify is using macros, but I like that this is very usable without macros. 

It seems the `test-drive`'s internal code is relatively straightforward and I think we should be able to maintain this as a community.

So +1 to move under fortran-lang.

**Comment by awvwgk** [comment]
Alright, I'll went ahead and transferred the repository to @fortran-lang.

**Comment by awvwgk** [comment]
> Why not simplify:
> 
> ```fortran
>             call check(error, all(input == expected))
>             if (allocated(error)) return
> ```
> 
> to:
> 
> ```fortran
>             if (check(error, all(input == expected))) return
> ```
> 
> Beyond that, the only other way to simplify is using macros, but I like that this is very usable without macros.

Let's continue this discussion in a separate issue.

**Comment by certik** [comment]
See #3.
